config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="display-4">Update Task</h1>
  <br>
  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.submit %>
  <% end %>
  <br>
  <%= link_to "Cancel", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="display-4">Tasks</h1>
  <% @tasks.each do |task| %>
    <% if task.completed %>
      <input type="checkbox" name="<%= task.title %>" value="<%= task.title %>" checked>
      <label for="<%= task.title %>"><%= link_to task.title, task_path(task) %></label>
      <br>
    <% else %>
      <input type="checkbox" name="<%= task.title %>" value="<%= task.title %>">
      <label for="<%= task.title %>"><%= link_to task.title, task_path(task) %></label>
      <br>
    <% end %>
  <% end %>
  <br>
  <%= link_to "Create new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="display-4">Create new Task</h1>
  <br>
  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.submit %>
  <% end %>
  <br>
  <%= link_to "Cancel", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="display-4"><%= @task.title %></h1>
  <p>
    <% if @task.completed %>
      <input type="checkbox" name="<%= @task.title %>" value="<%= @task.title %>" checked>
    <% else %>
      <input type="checkbox" name="<%= @task.title %>" value="<%= @task.title %>">
    <% end %>
  </p>
  <p><%= @task.details %></p>
  <%= link_to "Edit task", task_edit_path %>
  <br>
  <%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
  <br>
  <%= link_to "Back to task overview.", tasks_path %>
</div>